In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [9]:
#indexes where the value are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [13]:
#sarting the array
arr=np.array([3,2,0,1])
print("\nOriginal array",arr)
print("\nsarted array",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\noriginal array",arr)
print("\nsarted array",np.sort(arr))


Original array [3 2 0 1]

sarted array [0 1 2 3]

original array [[3 2 4]
 [5 0 1]]

sarted array [[2 3 4]
 [0 1 5]]


In [15]:
sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print(values)
print(insert_indices)

[1 3 5 7]
[2, 4, 6]
[1 2 3]


In [2]:
#filter
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [4]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

Filter array: [43 44]
