In [6]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original array")
print(a)
print(b)
print("\nvector addition")
print(a+b)
print("\nvector subtraction")
print(a-b)
print("\nvector multiplication")
print(a*b)
print("\nvector divition")
print(a/b)
print("\nvector dot product")
print(a.dot(b))
print("\nscalar multiplication")
sclr=5
print("scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)
#numpyprint(\nvector)
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
print("\n\nNumpy.vectorize method")
print("return x-y if x>y,otherwise return x+y")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("result:",vec_func(arr1,arr2))


Original array
[10 20 30 40 50]
[ 2  4  5  8 10]

vector addition
[12 24 35 48 60]

vector subtraction
[ 8 16 25 32 40]

vector multiplication
[ 20  80 150 320 500]

vector divition
[5. 5. 6. 5. 5.]

vector dot product
1070

scalar multiplication
scalar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]


Numpy.vectorize method
return x-y if x>y,otherwise return x+y
array1: [10, 4, 20]
array2: [2, 3, 30]
result: [ 8  1 50]
